// FlashAttention-3's pipelining, minus the parts that need CUDA. Generated by
// ops/flash_attention/tools/generate.ts — edit tools/fa3.wgsl.ts and
// regenerate rather than editing this file.
//
// Layout:
//   q:      [B, H, L, D]  f32, row-major
//   k:      [B, H, S, D]  f32
//   v:      [B, H, S, Dv] f32
//   mask:   broadcast over [mask_batch, mask_heads, mask_rows, S]
//   output: [B, H, L, Dv] f32

struct Params {
  H: u32, L: u32, S: u32, D: u32, Dv: u32,
  scale: f32, causal: u32, query_offset: i32,
  mask_batch: u32, mask_heads: u32, mask_rows: u32,
}

@group(0) @binding(0) var<storage, read> q: array<f32>;
@group(0) @binding(1) var<storage, read> k: array<f32>;
@group(0) @binding(2) var<storage, read> v: array<f32>;
@group(0) @binding(3) var<storage, read> mask: array<f32>;
@group(0) @binding(4) var<storage, read_write> output: array<f32>;
@group(0) @binding(5) var<uniform> params: Params;

const BQ: u32 = 32u;
const TILE_S: u32 = 8u;
const THREADS: u32 = 128u;
const MAX_D: u32 = 128u;
const MAX_DV: u32 = 128u;
const K_STRIDE: u32 = 264u;
const ROW: u32 = 33u;
const V_STRIDE: u32 = 1024u;
const MASKED: f32 = -3.402823e+38;

var<workgroup> sq: array<vec4<f32>, 1056>;
var<workgroup> sk: array<vec4<f32>, 528>;
var<workgroup> sv: array<f32, 2048>;
var<workgroup> ss: array<f32, 256>;
// The softmax state, per row, **shared**.
//
// It used to be m[BQ] and l[BQ] in every thread's registers, which is where BQ
// stopped: they are per-row values, so every thread owning a channel of the
// same row held its own identical copy. At BQ=16 that is 32 f32 of duplicate
// state per thread on top of the accumulators, and BQ=32 measured *slower*
// than BQ=16 for that reason while workgroup storage sat two-thirds empty.
var<workgroup> smax: array<f32, 32>;
var<workgroup> ssum: array<f32, 32>;
var<workgroup> scorr: array<f32, 32>;

@compute @workgroup_size(128)
fn main(
  @builtin(workgroup_id) wg: vec3<u32>,
  @builtin(local_invocation_index) tid: u32,
) {
  let q0 = wg.x * BQ;
  let batch = wg.z;
  let h = wg.y;
  let head = batch * params.H + h;
  let k_head = head * params.S * params.D;
  let v_head = head * params.S * params.Dv;

  let mb = select(0u, batch, params.mask_batch > 1u);
  let mh = select(0u, h, params.mask_heads > 1u);

  let d4n = (params.D + 3u) / 4u;
  for (var t = tid; t < BQ * d4n; t = t + THREADS) {
    let r = t / d4n;
    let unit = t % d4n;
    let c0 = unit * 4u;
    let row = q0 + r;
    var val = vec4<f32>(0.0, 0.0, 0.0, 0.0);
    if (row < params.L) {
      for (var c = 0u; c < 4u; c = c + 1u) {
        let d = c0 + c;
        if (d < params.D) { val[c] = q[(head * params.L + row) * params.D + d]; }
      }
    }
    sq[r * ROW + unit] = val;
  }

  // One running maximum, sum and accumulator per (row this thread owns,
  // channel this thread owns). A thread owns one channel per sweep, and sweeps
  // until Dv is covered — Dv can exceed the workgroup (the tests go to 300),
  // which the first version silently truncated to the first THREADS channels.
  const SWEEPS: u32 = 1u;
  var acc: array<array<f32, SWEEPS>, BQ>;
  for (var r = 0u; r < BQ; r = r + 1u) {
    for (var p = 0u; p < SWEEPS; p = p + 1u) { acc[r][p] = 0.0; }
  }
  if (tid < BQ) { smax[tid] = MASKED; ssum[tid] = 0.0; }

  let tiles = (params.S + TILE_S - 1u) / TILE_S;

  // Prime the pipeline: tile 0 into half 0, before the loop.
  // D and Dv can differ; k and v are staged with their own strides rather
  // than one shared constant.
  for (var e = tid; e < TILE_S * d4n; e = e + THREADS) {
    let j = (0u) + e / d4n;
    let unit = e % d4n;
    let c0 = unit * 4u;
    var val = vec4<f32>(0.0, 0.0, 0.0, 0.0);
    if (j < params.S) {
      for (var c = 0u; c < 4u; c = c + 1u) {
        let d = c0 + c;
        if (d < params.D) { val[c] = k[k_head + j * params.D + d]; }
      }
    }
    sk[(0u) * K_STRIDE + (e / d4n) * ROW + unit] = val;
  }
  for (var e = tid; e < TILE_S * params.Dv; e = e + THREADS) {
    let j = (0u) + e / params.Dv;
    let d = e % params.Dv;
    sv[(0u) * V_STRIDE + e] = select(0.0, v[v_head + j * params.Dv + d], j < params.S);
  }

  var cur = 0u;
  for (var t = 0u; t < tiles; t = t + 1u) {
    let base = t * TILE_S;
    // Half `cur` now holds tile t, and half `1 - cur` was last read during
    // the previous iteration's accumulate — so both "tile t is visible" and
    // "the other half is free to overwrite" hold past this one barrier.
    workgroupBarrier();

      if (t + 1u < tiles) {
        // D and Dv can differ; k and v are staged with their own strides rather
        // than one shared constant.
        for (var e = tid; e < TILE_S * d4n; e = e + THREADS) {
          let j = ((t + 1u) * TILE_S) + e / d4n;
          let unit = e % d4n;
          let c0 = unit * 4u;
          var val = vec4<f32>(0.0, 0.0, 0.0, 0.0);
          if (j < params.S) {
            for (var c = 0u; c < 4u; c = c + 1u) {
              let d = c0 + c;
              if (d < params.D) { val[c] = k[k_head + j * params.D + d]; }
            }
          }
          sk[(1u - cur) * K_STRIDE + (e / d4n) * ROW + unit] = val;
        }
        for (var e = tid; e < TILE_S * params.Dv; e = e + THREADS) {
          let j = ((t + 1u) * TILE_S) + e / params.Dv;
          let d = e % params.Dv;
          sv[(1u - cur) * V_STRIDE + e] = select(0.0, v[v_head + j * params.Dv + d], j < params.S);
        }
      }

    for (var e = tid; e < BQ * TILE_S; e = e + THREADS) {
      let r = e / TILE_S;
      let slot = e % TILE_S;
      let j = (base) + slot;
      let row = q0 + r;
      var value = MASKED;
      if (j < params.S && row < params.L
          && (params.causal == 0u || i32(j) <= i32(row) + params.query_offset)) {
        var acc4 = vec4<f32>(0.0, 0.0, 0.0, 0.0);
        for (var dv = 0u; dv < d4n; dv = dv + 1u) {
          acc4 = fma(sq[r * ROW + dv], sk[(cur) * K_STRIDE + slot * ROW + dv], acc4);
        }
        let dot_ = acc4.x + acc4.y + acc4.z + acc4.w;
        let mr = select(0u, row, params.mask_rows > 1u);
        value = dot_ * params.scale + mask[((mb * params.mask_heads + mh) * params.mask_rows + mr) * params.S + j];
      }
      ss[e] = value;
    }
    workgroupBarrier();

    if (tid < BQ) {
      var best = MASKED;
      for (var slot = 0u; slot < TILE_S; slot = slot + 1u) { best = max(best, ss[tid * TILE_S + slot]); }
      let m_new = max(smax[tid], best);
      let corr = select(exp(smax[tid] - m_new), 0.0, smax[tid] == MASKED);
      var sum = 0.0;
      for (var slot = 0u; slot < TILE_S; slot = slot + 1u) {
        let s = ss[tid * TILE_S + slot];
        let w = select(exp(s - m_new), 0.0, s == MASKED);
        ss[tid * TILE_S + slot] = w;
        sum = sum + w;
      }
      ssum[tid] = ssum[tid] * corr + sum;
      scorr[tid] = corr;
      smax[tid] = m_new;
    }
    workgroupBarrier();

    for (var r = 0u; r < BQ; r = r + 1u) {
      let corr = scorr[r];
      for (var p = 0u; p < SWEEPS; p = p + 1u) { acc[r][p] = acc[r][p] * corr; }
    }
    for (var slot = 0u; slot < TILE_S; slot = slot + 1u) {
      var p = 0u;
      for (var c = tid; c < params.Dv; c = c + THREADS) {
        let value = sv[(cur) * V_STRIDE + slot * params.Dv + c];
        for (var r = 0u; r < BQ; r = r + 1u) {
          acc[r][p] = fma(ss[r * TILE_S + slot], value, acc[r][p]);
        }
        p = p + 1u;
      }
    }

    cur = 1u - cur;
  }

  workgroupBarrier();
  for (var r = 0u; r < BQ; r = r + 1u) {
    let row = q0 + r;
    if (row >= params.L) { continue; }
    let denom = ssum[r];
    var p = 0u;
    for (var c = tid; c < params.Dv; c = c + THREADS) {
      output[(head * params.L + row) * params.Dv + c] = select(acc[r][p] / denom, 0.0, denom == 0.0);
      p = p + 1u;
    }
  }
}
