/**
 * FlashAttention-2, as this device can express it.
 *
 * Issue #177. The generation is named for what it does, not for flattery: the
 * two things that separate FA2 from FA1 are both here.
 *
 *   - **The `1 / l` division is deferred to the epilogue.** FA1 renormalises
 *     the accumulator every tile; FA2 keeps it unnormalised, carries the
 *     running sum, and divides once at the end. See `parts.ts`'s `softmax` and
 *     `epilogue`.
 *   - **The work is partitioned over queries, not keys.** One workgroup owns
 *     `BQ` query rows for the whole sequence, so no cross-workgroup reduction
 *     is needed and `k`/`v` traffic falls by a factor of `BQ`.
 *
 * That second one is the only thing that ever moved this op. Reading the first
 * version suggested three fixes — the score phase used 64 of 256 threads, the
 * accumulate phase 128 of 256, and `q` was re-read from global `S` times — and
 * all three together measured **1.0x**, because the arithmetic says:
 *
 *     one workgroup = one query row
 *     FLOPs   2 * S * D  (scores) + 2 * S * Dv (accumulate) = 2.02 M
 *     bytes   S * D * 4  (all of k) + S * Dv * 4 (all of v) = 4.05 MB
 *     -> 0.50 FLOP/byte, against a measured roofline crossover of 30
 *
 * Memory-bound by a factor of sixty, so no rearrangement of the arithmetic
 * moves it. `BQ = 16` divides the traffic by sixteen and is what the shipped
 * kernel does.
 *
 * **What FA2 does not do is overlap anything.** Its tile loop stages, waits,
 * scores, waits, softmaxes, waits, accumulates, waits: four barriers, and the
 * global loads for the next tile do not begin until the current tile is
 * finished with. That is `fa3.wgsl.ts`'s subject.
 */
import { accumulate, epilogue, preamble, prologue, scores, softmax, stageTile } from "./parts.js";
import type { FlashShape } from "./shape.js";

/**
 * `q: [B, H, L, D]`, `k: [B, H, S, D]`, `v: [B, H, S, Dv]` to
 * `output: [B, H, L, Dv]`, dispatched `[ceil(L / BQ), H, B]`.
 *
 * **The grid is not one workgroup per query** — it is per `BQ` queries.
 */
export function fa2Flash(shape: FlashShape, maxD: number, maxDv = maxD): string {
  return `// FlashAttention-2. Generated by ops/flash_attention/tools/generate.ts — edit
// tools/fa2.wgsl.ts and regenerate rather than editing this file.
//
// Layout:
//   q:      [B, H, L, D]  f32, row-major
//   k:      [B, H, S, D]  f32
//   v:      [B, H, S, Dv] f32
//   mask:   broadcast over [mask_batch, mask_heads, mask_rows, S]
//   output: [B, H, L, Dv] f32
${preamble(shape, maxD, maxDv, "fa2")}
@compute @workgroup_size(${shape.threads})
fn main(
  @builtin(workgroup_id) wg: vec3<u32>,
  @builtin(local_invocation_index) tid: u32,
) {
${prologue(shape, shape.threads, maxDv)}
  for (var t = 0u; t < tiles; t = t + 1u) {
    let base = t * TILE_S;
    workgroupBarrier();
${stageTile("base", "0u", "    ")}
    workgroupBarrier();

    // Scores: both operands come out of workgroup memory, which is the point.
${scores("base", "0u", "    ")}
    workgroupBarrier();

${softmax("    ")}
    workgroupBarrier();

${accumulate(shape.accumulate, "0u", "    ")}
  }

${epilogue()}
}
`;
}
