import { readFileSync } from "node:fs";
import type { LlamaConfig } from "./config.js";
import { assertWeightShapes, type LlamaLayerWeights, type LlamaWeights } from "./weights.js";

/**
 * Loads `llm/fixtures/tiny.*`, generated by `llm/tools/gen_fixture.py`.
 *
 * Three files, deliberately not one npz: `tiny.manifest.json` is small and
 * human-diffable (shapes, seeds, token IDs — the things worth seeing in a
 * `git diff`), while the weight and logit tensors live in plain f32
 * little-endian binaries with byte offsets the manifest records. Reading a
 * flat `Float32Array` view out of a `Buffer` needs nothing beyond `node:fs` —
 * no npz/zip dependency for a format this repository does not otherwise use.
 */

interface WeightManifestEntry {
  name: string;
  shape: number[];
  /** Offset into `tiny.weights.bin`, in f32 elements (not bytes). */
  offset: number;
}

interface FixtureManifest {
  config: {
    numLayers: number;
    hiddenSize: number;
    numHeads: number;
    numKvHeads: number;
    headDim: number;
    ffnHidden: number;
    vocabSize: number;
    ropeTheta: number;
    rmsNormEps: number;
    tieEmbeddings: boolean;
  };
  promptTokens: number[];
  decodeTokens: number[];
  weights: WeightManifestEntry[];
  logits: {
    prefill: { shape: number[]; offset: number };
    decode: { shape: number[]; offset: number };
  };
}

export interface LoadedFixture {
  config: LlamaConfig;
  weights: LlamaWeights;
  promptTokens: number[];
  decodeTokens: number[];
  /** One `[vocabSize]` row per prompt token. */
  prefillLogits: Float32Array[];
  /** One `[vocabSize]` row per decode step. */
  decodeLogits: Float32Array[];
}

function elementsOf(shape: number[]): number {
  return shape.reduce((a, b) => a * b, 1);
}

/** A `Float32Array` view into `buffer` at `offset` f32 elements, `length` elements long — no copy. */
function view(buffer: Buffer, offset: number, length: number): Float32Array {
  return new Float32Array(buffer.buffer, buffer.byteOffset + offset * 4, length);
}

export function loadTinyFixture(fixturesDir: string | URL = new URL("./fixtures/", import.meta.url)): LoadedFixture {
  const dir = fixturesDir instanceof URL ? fixturesDir : new URL(fixturesDir);
  const manifest: FixtureManifest = JSON.parse(readFileSync(new URL("tiny.manifest.json", dir), "utf8"));
  const weightsBuf = readFileSync(new URL("tiny.weights.bin", dir));
  const logitsBuf = readFileSync(new URL("tiny.logits.bin", dir));

  const byName = new Map<string, Float32Array>();
  for (const entry of manifest.weights) {
    byName.set(entry.name, view(weightsBuf, entry.offset, elementsOf(entry.shape)));
  }
  const get = (name: string): Float32Array => {
    const found = byName.get(name);
    if (!found) throw new Error(`tiny.manifest.json: no weight named ${JSON.stringify(name)}`);
    return found;
  };

  const config: LlamaConfig = {
    numLayers: manifest.config.numLayers,
    hiddenSize: manifest.config.hiddenSize,
    numHeads: manifest.config.numHeads,
    numKvHeads: manifest.config.numKvHeads,
    headDim: manifest.config.headDim,
    ffnHidden: manifest.config.ffnHidden,
    vocabSize: manifest.config.vocabSize,
    ropeTheta: manifest.config.ropeTheta,
    rmsNormEps: manifest.config.rmsNormEps,
    // Generous headroom past prompt + decode steps; the fixture itself only
    // ever reaches promptTokens.length + decodeTokens.length.
    maxSeqLen: manifest.promptTokens.length + manifest.decodeTokens.length + 8,
    tieEmbeddings: manifest.config.tieEmbeddings,
  };

  const layers: LlamaLayerWeights[] = [];
  for (let i = 0; i < config.numLayers; i += 1) {
    layers.push({
      attnNorm: get(`layers.${i}.attnNorm`),
      wq: get(`layers.${i}.wq`),
      wk: get(`layers.${i}.wk`),
      wv: get(`layers.${i}.wv`),
      wo: get(`layers.${i}.wo`),
      ffnNorm: get(`layers.${i}.ffnNorm`),
      wGate: get(`layers.${i}.wGate`),
      wUp: get(`layers.${i}.wUp`),
      wDown: get(`layers.${i}.wDown`),
    });
  }

  const weights: LlamaWeights = {
    embedTokens: get("embedTokens"),
    layers,
    finalNorm: get("finalNorm"),
    lmHead: get("lmHead"),
  };
  assertWeightShapes(config, weights);

  const prefillLogits: Float32Array[] = [];
  const [prefillN, vocabA] = manifest.logits.prefill.shape as [number, number];
  for (let t = 0; t < prefillN; t += 1) {
    prefillLogits.push(view(logitsBuf, manifest.logits.prefill.offset + t * vocabA, vocabA));
  }
  const decodeLogits: Float32Array[] = [];
  const [decodeN, vocabB] = manifest.logits.decode.shape as [number, number];
  for (let t = 0; t < decodeN; t += 1) {
    decodeLogits.push(view(logitsBuf, manifest.logits.decode.offset + t * vocabB, vocabB));
  }

  return {
    config,
    weights,
    promptTokens: manifest.promptTokens,
    decodeTokens: manifest.decodeTokens,
    prefillLogits,
    decodeLogits,
  };
}
