import { readFileSync } from "node:fs";
import type { LlamaConfig } from "./config.js";
import type { LlamaWeightsQ8 } from "./weights-q8.js";
import { assertWeightShapesQ8 } from "./weights-q8.js";
import { buildLlamaWeightsQ8, llamaConfigFromManifest, type WeightManifestConfig, type WeightManifestEntry } from "./weights-q8-io.js";

/**
 * Loads `llm/fixtures/tiny_q8.*`, generated by `llm/tools/gen_fixture_q8.py`
 * — issue #105's counterpart to `fixture.ts#loadTinyFixture`, for the
 * quantization-aware reference `LlamaEngineQ8`'s parity test checks against.
 *
 * The weight-manifest parsing itself (`{name, kind, shape, offsets}` ->
 * `LlamaWeightsQ8`) is `weights-q8-io.ts#buildLlamaWeightsQ8`, shared with
 * the real-model loader `llm/tools/convert_weights.py`'s output feeds —
 * this file's own job is just the tiny fixture's filenames and its extra
 * prompt-token / logit sections, which a real converted checkpoint has no
 * equivalent of (nothing "ran transformers" to produce them).
 *
 * Four binary files rather than `fixture.ts`'s two, because a `QuantizedLinear`
 * carries two element types (`Int8Array` codes, `Float32Array` scale) that
 * cannot share one little-endian buffer without a dtype tag per entry — kept
 * apart entirely instead: `tiny_q8.codes.bin` (int8), `tiny_q8.scales.bin`
 * (f32, one segment per quantized entry), `tiny_q8.norms.bin` (f32, the
 * unquantized norm weights), `tiny_q8.logits.bin` (f32, same prefill/decode
 * convention as `fixture.ts`).
 */

interface FixtureManifest {
  config: WeightManifestConfig;
  promptTokens: number[];
  decodeTokens: number[];
  weights: WeightManifestEntry[];
  logits: {
    prefill: { shape: [number, number]; offset: number };
    decode: { shape: [number, number]; offset: number };
  };
}

export interface LoadedFixtureQ8 {
  config: LlamaConfig;
  weights: LlamaWeightsQ8;
  promptTokens: number[];
  decodeTokens: number[];
  prefillLogits: Float32Array[];
  decodeLogits: Float32Array[];
}

function f32View(buffer: Buffer, offset: number, length: number): Float32Array {
  return new Float32Array(buffer.buffer, buffer.byteOffset + offset * 4, length);
}

/** A copy of `buffer`'s bytes as a plain `ArrayBuffer` — `buildLlamaWeightsQ8` indexes from byte 0 of what it is given, but a `Buffer`'s own `.buffer` is the whole underlying allocation, not necessarily starting at this `Buffer`'s own offset. */
function toArrayBuffer(buffer: Buffer): ArrayBuffer {
  return buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength) as ArrayBuffer;
}

export function loadTinyFixtureQ8(fixturesDir: string | URL = new URL("./fixtures/", import.meta.url)): LoadedFixtureQ8 {
  const dir = fixturesDir instanceof URL ? fixturesDir : new URL(fixturesDir);
  const manifest: FixtureManifest = JSON.parse(readFileSync(new URL("tiny_q8.manifest.json", dir), "utf8"));
  const codesBuf = readFileSync(new URL("tiny_q8.codes.bin", dir));
  const scalesBuf = readFileSync(new URL("tiny_q8.scales.bin", dir));
  const normsBuf = readFileSync(new URL("tiny_q8.norms.bin", dir));
  const logitsBuf = readFileSync(new URL("tiny_q8.logits.bin", dir));

  const config = llamaConfigFromManifest(
    manifest.config,
    manifest.promptTokens.length + manifest.decodeTokens.length + 8,
  );
  const weights = buildLlamaWeightsQ8(
    manifest.weights,
    toArrayBuffer(codesBuf),
    toArrayBuffer(scalesBuf),
    toArrayBuffer(normsBuf),
    config.numLayers,
  );
  assertWeightShapesQ8(config, weights);

  const prefillLogits: Float32Array[] = [];
  const [prefillN, vocabA] = manifest.logits.prefill.shape;
  for (let t = 0; t < prefillN; t += 1) {
    prefillLogits.push(f32View(logitsBuf, manifest.logits.prefill.offset + t * vocabA, vocabA));
  }
  const decodeLogits: Float32Array[] = [];
  const [decodeN, vocabB] = manifest.logits.decode.shape;
  for (let t = 0; t < decodeN; t += 1) {
    decodeLogits.push(f32View(logitsBuf, manifest.logits.decode.offset + t * vocabB, vocabB));
  }

  return {
    config,
    weights,
    promptTokens: manifest.promptTokens,
    decodeTokens: manifest.decodeTokens,
    prefillLogits,
    decodeLogits,
  };
}
