#!/usr/bin/env python3
"""Generates ops/rope/axes-cases.ts — what `ropeAxes` is checked against.

Rule 7 says to follow the reference implementation rather than invent a
convention, and multi-axis RoPE has no `torch` equivalent to defer to. The
reference here is therefore the model the op exists for:

    Tongyi-MAI/Z-Image @ 26f23eda626ffadda020b04ff79488e1d72004cd
    src/zimage/transformer.py — `RopeEmbedder`, `apply_rotary_emb`
    src/config/model.py       — ROPE_THETA = 256.0, ROPE_AXES_DIMS = [32, 48, 48]

Those two functions are **imported, not transcribed**. A transcription is a
second copy that agrees with the original only until someone edits one of them,
and the whole value of this fixture is that it is upstream's own arithmetic.

## Reproducing

    git clone https://github.com/Tongyi-MAI/Z-Image.git
    ZIMAGE_SRC=$PWD/Z-Image/src python3 ops/rope/tools/gen_axes_fixture.py

Needs `torch` only (2.10.0+cu128 when this was generated); no weights are
loaded, since `RopeEmbedder` holds no parameters — the whole op is a function of
the head geometry and the token's position on each axis.

## Why only the outputs are written

The input is `sin(i * 0.29) * 2`, generated identically on both sides — in f64
and rounded to f32 here, exactly as `Float32Array.from(Math.sin(...))` does in
the test. Writing 1500 more floats to restate a one-line formula would make the
fixture harder to read without making it stricter: an input the test built
differently would disagree at the third digit, not at the seventh.
"""

import json
import os
import sys

import torch

sys.path.insert(0, os.environ.get("ZIMAGE_SRC", "Z-Image/src"))

from zimage.transformer import RopeEmbedder, apply_rotary_emb  # noqa: E402

# Small enough to read, large enough to be wrong in a visible way. Each case
# names what an implementation would have to get right to reproduce it; see the
# comments carried into the generated file.
CASES = [
    (
        "zimage",
        "Z-Image's own geometry and theta. Head dim 128 split 32/48/48, so the "
        "three axes cover different channel counts and the exponent's "
        "denominator differs per axis.",
        [32, 48, 48],
        256.0,
        [0, 0, 0, 1, 2, 3],
        2,
        1,
    ),
    (
        "uneven",
        "Unequal, small axes with every position distinct: an implementation "
        "that divided by head_dim instead of the axis dim, or that used axis "
        "0's position for every axis, disagrees here.",
        [4, 6, 6],
        256.0,
        [0, 1, 2, 3, 0, 5, 9, 9, 0],
        3,
        2,
    ),
    (
        "two",
        "Two axes at the 1-D theta of 10000, so the base is exercised as a "
        "knob rather than as Z-Image's constant.",
        [8, 8],
        10000.0,
        [0, 1, 5, 2],
        2,
        2,
    ),
    (
        "single",
        "One axis is ordinary 1-D RoPE, and upstream agrees with it — which is "
        "the same claim `ropeAxes matches rope` makes against this "
        "repository's own 1-axis op, arrived at from the other side.",
        [16],
        10000.0,
        [0, 1, 2],
        3,
        2,
    ),
]


def run(axis_dims, theta, ids, n, heads):
    head_dim = sum(axis_dims)
    # `axes_lens` only sizes upstream's precomputed table; every position used
    # here is inside it, so it is not part of what this fixture pins. `ropeAxes`
    # has no such table and therefore no such parameter.
    embedder = RopeEmbedder(theta=theta, axes_dims=axis_dims, axes_lens=[64] * len(axis_dims))
    freqs = embedder(torch.tensor(ids, dtype=torch.long).reshape(n, len(axis_dims)))

    # f64 sine rounded to f32, which is what `Math.sin` into a `Float32Array`
    # gives the test on the other side.
    x = ((torch.arange(n * heads * head_dim, dtype=torch.float64) * 0.29).sin() * 2.0).float()
    # `apply_rotary_emb` takes [batch, tokens, heads, head_dim] and unsqueezes
    # the frequencies at the head axis, so one batch of `n` tokens.
    out = apply_rotary_emb(x.reshape(1, n, heads, head_dim), freqs.unsqueeze(0))
    return [float(v) for v in out.reshape(-1).tolist()]


def main():
    lines = [
        "/**",
        " * What `ropeAxes` is checked against: Z-Image's own RoPE, run by Z-Image.",
        " *",
        " * Generated by `ops/rope/tools/gen_axes_fixture.py` — do not edit by hand.",
        " * Produced by importing upstream's `RopeEmbedder` and `apply_rotary_emb` from",
        " *",
        " *   Tongyi-MAI/Z-Image @ 26f23eda626ffadda020b04ff79488e1d72004cd",
        " *   src/zimage/transformer.py",
        " *",
        " * with torch 2.10.0+cu128 on CPU. The generator's docstring says why the",
        " * functions are imported rather than transcribed, and why the input is a",
        " * formula here rather than 1500 more floats.",
        " */",
        "",
        "export interface AxesCase {",
        "  name: string;",
        "  /** What this case would catch. */",
        "  why: string;",
        "  axisDims: number[];",
        "  thetaBase: number;",
        "  /** `[N, axisDims.length]`, token-major. */",
        "  positions: number[];",
        "  N: number;",
        "  numHeads: number;",
        "  /** `[N, numHeads, sum(axisDims)]`, from upstream. */",
        "  output: number[];",
        "}",
        "",
        "/**",
        " * The input every case is run on: `sin(i * 0.29) * 2`, the same expression",
        " * the generator evaluates in f64 before rounding to f32.",
        " */",
        "export const axesCaseInput = (length: number): Float32Array =>",
        "  Float32Array.from({ length }, (_, i) => Math.sin(i * 0.29) * 2);",
        "",
        "export const AXES_CASES: AxesCase[] = [",
    ]
    for name, why, axis_dims, theta, ids, n, heads in CASES:
        out = run(axis_dims, theta, ids, n, heads)
        lines += [
            "  {",
            f"    name: {json.dumps(name)},",
            f"    why: {json.dumps(why)},",
            f"    axisDims: {axis_dims},",
            f"    thetaBase: {theta},",
            f"    positions: {ids},",
            f"    N: {n},",
            f"    numHeads: {heads},",
            "    output: [",
        ]
        for i in range(0, len(out), 6):
            lines.append("      " + ", ".join(repr(v) for v in out[i : i + 6]) + ",")
        lines += ["    ],", "  },"]
    lines += ["];", ""]

    path = os.path.join(os.path.dirname(__file__), "..", "axes-cases.ts")
    with open(os.path.normpath(path), "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {os.path.normpath(path)}")


if __name__ == "__main__":
    main()
