#!/usr/bin/env python3
"""Generates ops/rope/h3-cases.ts — MiniMax-H3's 3D RoPE, run by H3's own code.

Issue #200. `ropeAxes` took integer positions until this model: H3's visual VAE
normalises each axis to `(-1, 1)` — `2 * (i + 0.5) / n - 1` — and multiplies the
angle by `2*pi`, so its positions are fractional. A rotation by a fractional
angle is the same rotation, and the binding is `f32` now.

This fixture pins the whole mapping, not just the capability, because the
mapping is where a port goes wrong silently:

  - **the frequencies already agree.** H3 builds
    `theta ** -arange(0, 1, 2 * n_dim / rot_dim)` — eight exponents
    `[0, 1/8, ..., 7/8]` for `rot_dim = 48, n_dim = 3` — and `ropeAxes` builds
    `theta ** -(2 * pair / axis_dim)` over a 16-channel axis, which is the same
    eight. Nothing had to change for that.
  - **the pairing does not.** H3 tiles `[t8, h8, w8]` twice and rotates halves
    (channel `c` with `c + 24`); `ropeAxes` pairs adjacent channels inside each
    axis block. `H3_ROPE_PERMUTATION` below converts one to the other, and it is
    applied to the *weights* once at conversion, exactly as `permuteForRope`
    does for Anima.
  - **only 48 of 64 channels rotate.** A fourth axis pinned at position 0 is the
    identity — `cos 0 = 1`, `sin 0 = 0` — so `axisDims [16, 16, 16, 16]` covers
    the sixteen H3 leaves alone without a second code path.

The source is transcribed here rather than imported, and that is a weaker
guarantee than `gen_axes_fixture.py`'s: H3's bundle ships as remote code inside
the checkpoint rather than as a repository, and `RotaryEmbeddingND` pulls in
diffusers, distributed helpers and a flash-attention import to be constructed.
The three functions below are copied from

    MiniMaxAI/MiniMax-H3, FL2VA/video_vae/{base_module,func}.py

verbatim, and the copy is short enough to read against the original.

    python3 ops/rope/tools/gen_h3_fixture.py
"""

import json
import math
import pathlib
import sys

import torch

DIM_HEAD, ROT_DIM, N_DIM, THETA = 64, 48, 3, 100.0


def token_ids(dims):
    """`create_token_ids(..., id_type="length_normalized")`, func.py."""
    axes = []
    for n in dims:
        coords = torch.arange(0.5, n, dtype=torch.float32) / n
        axes.append(2.0 * coords - 1.0)
    return torch.stack(torch.meshgrid(*axes, indexing="ij"), dim=-1).flatten(0, len(dims) - 1)


def rope_tables(ids):
    """`RotaryEmbeddingND.forward` with `use_angle=True`, base_module.py."""
    inv_freq = 1 / THETA ** torch.arange(0, 1, 2 * N_DIM / ROT_DIM, dtype=torch.float32)
    angles = (2 * math.pi) * ids[:, :, None] * inv_freq[None, None, :]
    angles = angles.flatten(1, 2).tile(2)
    return torch.cos(angles), torch.sin(angles)


def apply_rope(t, cos, sin):
    """`_apply_rotary_pos_emb_impl` with `rot_dim < t_dim`, func.py."""

    def rotate_half(x):
        a, b = torch.chunk(x, 2, dim=-1)
        return torch.cat((-b, a), dim=-1)

    rot, keep = t[..., : cos.shape[-1]], t[..., cos.shape[-1] :]
    return torch.cat([rot * cos[:, None, :] + rotate_half(rot) * sin[:, None, :], keep], dim=-1)


def permutation():
    """H3 channel order -> `ropeAxes` channel order, per head.

    H3 channel `c < 48` carries axis `c % 24 // 8` at frequency `c % 8`, and is
    paired with `c + 24`. `ropeAxes` wants axis `a`'s block contiguous with
    adjacent pairs, so that channel lands at `a * 16 + 2 * f + half`.
    """
    perm = [0] * DIM_HEAD
    for c in range(ROT_DIM):
        half, rest = divmod(c, 24)
        axis, freq = divmod(rest, 8)
        perm[axis * 16 + 2 * freq + half] = c
    for c in range(ROT_DIM, DIM_HEAD):
        perm[c] = c
    return perm


def main():
    torch.manual_seed(20260826)
    T, H, W, heads = 2, 3, 4, 2
    ids = token_ids([T, H, W])
    cos, sin = rope_tables(ids)
    n = ids.shape[0]
    x = torch.randn(n, heads, DIM_HEAD)
    want = apply_rope(x, cos, sin)

    body = f'''/**
 * MiniMax-H3's 3D RoPE, as H3 computes it.
 *
 * Generated by `ops/rope/tools/gen_h3_fixture.py` — do not edit by hand.
 * Transcribed (not imported — see the generator's docstring) from
 *
 *   MiniMaxAI/MiniMax-H3, FL2VA/video_vae/{{base_module,func}}.py
 *   `RotaryEmbeddingND` (use_angle=True), `create_token_ids`,
 *   `_apply_rotary_pos_emb_impl`
 *
 * with torch {torch.__version__} on CPU. Issue #200.
 *
 * Positions here are **fractional**, which is the capability this fixture
 * exists for: `(-1, 1)` normalised coordinates times `2*pi`, not grid indices.
 */

/** H3 channel order to `ropeAxes` channel order, per head. Applied to weights. */
export const H3_ROPE_PERMUTATION: readonly number[] = {json.dumps(permutation())};

export const H3_ROPE_CASE = {{
  /** Latent extent, in the order `create_token_ids` meshes them. */
  patchDims: [{T}, {H}, {W}],
  numHeads: {heads},
  dimHead: {DIM_HEAD},
  rotDim: {ROT_DIM},
  thetaBase: {THETA},
  /** `[N, 3]`, already multiplied by `2*pi` — the angle, not the coordinate. */
  positions: {json.dumps([round(v, 9) for v in (2 * math.pi * ids).flatten().tolist()])},
  /** `[N, heads, dimHead]`, in **H3's** channel order. */
  input: {json.dumps([round(v, 7) for v in x.flatten().tolist()])},
  /** What H3 produces, in H3's channel order. */
  want: {json.dumps([round(v, 7) for v in want.flatten().tolist()])},
}} as const;
'''
    out = pathlib.Path(__file__).resolve().parents[1] / "h3-cases.ts"
    out.write_text(body)
    print(f"wrote {out} — {n} tokens, {x.numel()} values")
    return 0


if __name__ == "__main__":
    sys.exit(main())
