/**
 * Anima's whole DiT forward, composed from this repository's ops.
 *
 * Issue #170's second stage. `block.ts` is the repeated part and matches the
 * model at 3.221e-7 on real weights; this is everything around it, which is
 * where the conventions live and therefore where a port goes wrong. A stack of
 * correct blocks says nothing about any of the following, and every one of them
 * was read out of ComfyUI's `predict2.py` rather than assumed:
 *
 *  - **A padding-mask channel is concatenated before patchify** (`:806-813`).
 *    Zeros when no mask is given, which is every text-to-image call. That is
 *    why `x_embedder.proj` is `[2048, 68]` and not `[2048, 64]`: 16 latent
 *    channels plus one mask, times a 2x2 patch.
 *  - **`t_embedder` returns the *input* as the embedding when adaLN is a LoRA**
 *    (`:262-266`). `linear_1 -> SiLU -> linear_2` produces the *LoRA* term, and
 *    the conditioning the blocks read is `sample` — the raw sinusoidal
 *    embedding — passed straight through. Reading it the other way round gives
 *    a tensor of the right shape carrying the wrong thing.
 *  - **The sinusoidal embedding puts `cos` first** (`:236`), as Z-Image's does.
 *    The opposite of what diffusers usually writes.
 *  - **`t_embedding_norm` is an RMSNorm applied after** (`:836`) — the one
 *    RMSNorm in a model whose blocks are all LayerNorm.
 *  - **The final layer chunks into two**, `shift` and `scale`, with no gate
 *    (`:358`, `n_adaln_chunks = 2`).
 *  - **`unpatchify` unpacks `(p1 p2 t C)`** (`:372-378`) — the channel axis is
 *    *last* within a patch. Getting that order wrong produces a tensor of the
 *    right shape whose every pixel is a different combination.
 *  - **RoPE applies to self-attention only** (`:184`), and pairs channels half
 *    a head apart (HF's convention, not `ops/rope`'s adjacent pairs — see
 *    `weights-node.ts`). Its axis split for head_dim 128 is `t 44 / h 42 /
 *    w 42`, and for a single-frame image every `t` angle is zero.
 *
 * Correctness is `fixtures/forward.*`, generated by running ComfyUI's own model
 * with hooks on the intermediates — not by reading this file and agreeing.
 *
 * Deliberately CPU: this is `ops/*`'s reference path throughout, so it is a
 * statement about correctness only.
 */
import { ACTIVATION, activation } from "../../../ops/activation/index.js";
import { matmul } from "../../../ops/matmul/index.js";
import { rmsnorm } from "../../../ops/rmsnorm/index.js";
import { layernorm } from "../../../ops/layernorm/index.js";
import { type AnimaBlockConfig, type AnimaBlockWeights, animaBlock, ropeAxisDims, ropeBases } from "./block.js";

export interface AnimaConfig {
  numBlocks: number;
  modelChannels: number;
  numHeads: number;
  adalnLoraDim: number;
  inChannels: number;
  outChannels: number;
  patchSpatial: number;
  patchTemporal: number;
  crossattnEmbChannels: number;
  concatPaddingMask: boolean;
  /** `10000` inside the sinusoidal embedding — `Timesteps` (`predict2.py:228`). */
  maxPeriod: number;
  normEps: number;
  /** The checkpoint's own RoPE extrapolation ratios — 4.0 / 4.0 / 1.0 here. */
  ropeExtrapolation: { t: number; h: number; w: number };
}

/** Anything that hands back a tensor by name. */
export interface WeightSource {
  get(name: string): Float32Array;
  has(name: string): boolean;
  shapeOf?(name: string): number[] | undefined;
}

/** `nn.Linear`: `y = x @ W^T (+ b)`, `W` stored `[out, in]`. */
function linear(
  x: Float32Array,
  weight: Float32Array,
  rows: number,
  inDim: number,
  outDim: number,
  bias?: Float32Array,
): Float32Array {
  const wT = new Float32Array(inDim * outDim);
  for (let o = 0; o < outDim; o += 1) {
    for (let i = 0; i < inDim; i += 1) wT[i * outDim + o] = weight[o * inDim + i]!;
  }
  const out = matmul({ a: x, b: wT, M: rows, N: outDim, K: inDim });
  if (bias) {
    for (let r = 0; r < rows; r += 1) {
      for (let o = 0; o < outDim; o += 1) out[r * outDim + o] = out[r * outDim + o]! + bias[o]!;
    }
  }
  return out;
}

/**
 * The sinusoidal timestep embedding, `cos` first.
 *
 * `exponent = -log(10000) * arange(half) / half`, then
 * `cat([cos(t * exp(exponent)), sin(...)])` (`predict2.py:226-237`). Note the
 * division is by `half` rather than `half - 1`, which is a real difference from
 * some other implementations and shifts every frequency.
 */
export function timestepEmbedding(t: number, channels: number, maxPeriod: number): Float32Array {
  const half = Math.floor(channels / 2);
  const out = new Float32Array(channels);
  for (let i = 0; i < half; i += 1) {
    const arg = t * Math.exp((-Math.log(maxPeriod) * i) / half);
    out[i] = Math.cos(arg);
    out[half + i] = Math.sin(arg);
  }
  return out;
}

/**
 * `[C, T, H, W]` to `[T*H*W, C*pT*pH*pW]`, with the padding-mask channel added.
 *
 * The mask is a channel of zeros appended after the latent's own (`:812`), and
 * the patch packs **`(C, pT, pH, pW)` — channel first**. `PatchEmbed`'s own
 * `Rearrange` spells it `"b c (t r) (h m) (w n) -> b t h w (c r m n)"`
 * (`:300-302`).
 *
 * Z-Image puts the channel **last** within a patch, and writing that here from
 * memory cost a 3.5e-1 mismatch at the first block — a tensor of exactly the
 * right shape whose every row was a different linear combination. The two
 * models do not share this convention, and neither does this file's own
 * `unpatchify`, which unpacks `(pH, pW, pT, C)`.
 */
export function patchify(
  latent: Float32Array,
  channels: number,
  T: number,
  H: number,
  W: number,
  patch: number,
  patchT: number,
  withMask: boolean,
): Float32Array {
  const totalC = channels + (withMask ? 1 : 0);
  const tTokens = T / patchT;
  const hTokens = H / patch;
  const wTokens = W / patch;
  const patchDim = patchT * patch * patch * totalC;
  const out = new Float32Array(tTokens * hTokens * wTokens * patchDim);
  let at = 0;
  for (let tt = 0; tt < tTokens; tt += 1) {
    for (let ht = 0; ht < hTokens; ht += 1) {
      for (let wt = 0; wt < wTokens; wt += 1) {
        // `(c r m n)`: channel outermost, then the temporal and two spatial
        // offsets within the patch.
        for (let c = 0; c < totalC; c += 1) {
          for (let pt = 0; pt < patchT; pt += 1) {
            for (let ph = 0; ph < patch; ph += 1) {
              for (let pw = 0; pw < patch; pw += 1) {
                // The mask channel is zero: `torch.zeros(...)` when the caller
                // gives none, which text-to-image never does.
                if (c >= channels) {
                  out[at] = 0;
                } else {
                  const t = tt * patchT + pt;
                  const h = ht * patch + ph;
                  const w = wt * patch + pw;
                  out[at] = latent[((c * T + t) * H + h) * W + w]!;
                }
                at += 1;
              }
            }
          }
        }
      }
    }
  }
  return out;
}

/**
 * `[T*H*W, pH*pW*pT*C]` back to `[C, T, H, W]`.
 *
 * `"B T H W (p1 p2 t C) -> B C (T t) (H p1) (W p2)"` (`:372-378`) — so within a
 * patch the order is `pH, pW, pT, C`, which is **not** patchify's `pT, pH, pW,
 * C`. The two are not inverses by symmetry; they are inverses because the model
 * says so, and writing one from the other would be wrong.
 */
export function unpatchify(
  tokens: Float32Array,
  channels: number,
  T: number,
  H: number,
  W: number,
  patch: number,
  patchT: number,
): Float32Array {
  const tTokens = T / patchT;
  const hTokens = H / patch;
  const wTokens = W / patch;
  const out = new Float32Array(channels * T * H * W);
  let at = 0;
  for (let tt = 0; tt < tTokens; tt += 1) {
    for (let ht = 0; ht < hTokens; ht += 1) {
      for (let wt = 0; wt < wTokens; wt += 1) {
        for (let ph = 0; ph < patch; ph += 1) {
          for (let pw = 0; pw < patch; pw += 1) {
            for (let pt = 0; pt < patchT; pt += 1) {
              for (let c = 0; c < channels; c += 1) {
                const t = tt * patchT + pt;
                const h = ht * patch + ph;
                const w = wt * patch + pw;
                out[((c * T + t) * H + h) * W + w] = tokens[at]!;
                at += 1;
              }
            }
          }
        }
      }
    }
  }
  return out;
}

/** The tensor names one block needs, in the checkpoint's spelling. */
const BLOCK_TENSORS = [
  "self_attn.q_proj.weight", "self_attn.k_proj.weight", "self_attn.v_proj.weight",
  "self_attn.output_proj.weight", "self_attn.q_norm.weight", "self_attn.k_norm.weight",
  "cross_attn.q_proj.weight", "cross_attn.k_proj.weight", "cross_attn.v_proj.weight",
  "cross_attn.output_proj.weight", "cross_attn.q_norm.weight", "cross_attn.k_norm.weight",
  "mlp.layer1.weight", "mlp.layer2.weight",
  "adaln_modulation_self_attn.1.weight", "adaln_modulation_self_attn.2.weight",
  "adaln_modulation_cross_attn.1.weight", "adaln_modulation_cross_attn.2.weight",
  "adaln_modulation_mlp.1.weight", "adaln_modulation_mlp.2.weight",
] as const;

function collect(weights: WeightSource, index: number): AnimaBlockWeights {
  const out: Record<string, Float32Array> = {};
  for (const name of BLOCK_TENSORS) {
    out[name.replace(/\./g, "_")] = weights.get(`net.blocks.${index}.${name}`);
  }
  return out as unknown as AnimaBlockWeights;
}

/** What a caller can ask to be kept, to see where a mismatch starts. */
export interface AnimaTrace {
  tEmbed?: Float32Array;
  afterBlock0?: Float32Array;
  afterBlocks?: Float32Array;
}

export interface AnimaInput {
  /** `[inChannels, T, H, W]`, the noised latent. */
  latent: Float32Array;
  T: number;
  H: number;
  W: number;
  /** The diffusion time the model is called with. */
  t: number;
  /** `[contextSeq, crossattnEmbChannels]` from the adapter. */
  context: Float32Array;
}

/**
 * One denoising step's prediction: latent in, latent-shaped out.
 *
 * Batch is fixed at one, as in `examples/zimage` — the model supports more and
 * a batch axis threaded through a CPU reference path would be shape bookkeeping
 * with nothing to check it.
 */
export function animaForward(
  cfg: AnimaConfig,
  weights: WeightSource,
  input: AnimaInput,
  trace?: AnimaTrace,
): Float32Array {
  const { modelChannels: dim, numHeads, adalnLoraDim, inChannels, patchSpatial, patchTemporal, normEps } = cfg;
  const headDim = dim / numHeads;
  const { T, H, W } = input;
  const seq = (T / patchTemporal) * (H / patchSpatial) * (W / patchSpatial);
  const contextSeq = input.context.length / cfg.crossattnEmbChannels;
  const totalC = inChannels + (cfg.concatPaddingMask ? 1 : 0);
  const patchDim = patchTemporal * patchSpatial * patchSpatial * totalC;

  // --- timestep ---
  // `Timesteps(model_channels)` then `TimestepEmbedding(model_channels,
  // model_channels, use_adaln_lora=True)`. With the LoRA on, the *embedding* is
  // the sinusoidal `sample` itself and `linear_2`'s output is the LoRA term
  // (`predict2.py:262-266`) — the least intuitive line in this file.
  const sample = timestepEmbedding(input.t, dim, cfg.maxPeriod);
  const hidden = activation({
    input: linear(sample, weights.get("net.t_embedder.1.linear_1.weight"), 1, dim, dim),
    kind: ACTIVATION.silu,
  });
  const adalnLora = linear(hidden, weights.get("net.t_embedder.1.linear_2.weight"), 1, dim, 3 * dim);
  // `t_embedding_norm` is an RMSNorm, the one in a model of LayerNorms.
  const emb = rmsnorm({
    input: sample,
    weight: weights.get("net.t_embedding_norm.weight"),
    N: 1,
    D: dim,
    eps: normEps,
  });
  if (trace) trace.tEmbed = emb;

  // --- patchify and embed ---
  let x = linear(
    patchify(input.latent, inChannels, T, H, W, patchSpatial, patchTemporal, cfg.concatPaddingMask),
    weights.get("net.x_embedder.proj.1.weight"),
    seq,
    patchDim,
    dim,
    weights.has("net.x_embedder.proj.1.bias") ? weights.get("net.x_embedder.proj.1.bias") : undefined,
  );

  const axisDims = ropeAxisDims(headDim);
  const blockCfg: AnimaBlockConfig = {
    dim,
    numHeads,
    headDim,
    contextDim: cfg.crossattnEmbChannels,
    mlpHidden: weights.shapeOf?.("net.blocks.0.mlp.layer1.weight")?.[0] ??
      weights.get("net.blocks.0.mlp.layer1.weight").length / dim,
    adalnLoraDim,
    seq,
    contextSeq,
    normEps,
    ropeAxisDims: axisDims,
    ropeThetaPerAxis: ropeBases(axisDims, cfg.ropeExtrapolation),
  };

  // `(t, h, w)` per token, row-major over the token grid — `seq = arange(max(H,
  // W, T))` indexed per axis (`position_embedding.py:136-143`), so each axis's
  // position is simply its own coordinate.
  const tTokens = T / patchTemporal;
  const hTokens = H / patchSpatial;
  const wTokens = W / patchSpatial;
  const positions = new Int32Array(seq * 3);
  {
    let at = 0;
    for (let t = 0; t < tTokens; t += 1) {
      for (let h = 0; h < hTokens; h += 1) {
        for (let w = 0; w < wTokens; w += 1) {
          positions[at] = t;
          positions[at + 1] = h;
          positions[at + 2] = w;
          at += 3;
        }
      }
    }
  }

  for (let i = 0; i < cfg.numBlocks; i += 1) {
    x = animaBlock(blockCfg, collect(weights, i), x, emb, adalnLora, input.context, positions);
    if (trace && i === 0) trace.afterBlock0 = x.slice();
  }
  if (trace) trace.afterBlocks = x.slice();

  // --- final layer: LayerNorm without affine, then shift and scale, no gate ---
  const finalMod = (() => {
    const activated = activation({ input: emb.slice(), kind: ACTIVATION.silu });
    const inner = linear(activated, weights.get("net.final_layer.adaln_modulation.1.weight"), 1, dim, adalnLoraDim);
    const projected = linear(inner, weights.get("net.final_layer.adaln_modulation.2.weight"), 1, adalnLoraDim, 2 * dim);
    // The LoRA's **first two thirds** are added here — `adaln_lora[:, :, :2*D]`
    // (`predict2.py:381`). The final layer has two chunks where a block has
    // three, and takes the matching prefix rather than a separate term.
    for (let i = 0; i < projected.length; i += 1) projected[i] = projected[i]! + adalnLora[i]!;
    return { shift: projected.slice(0, dim), scale: projected.slice(dim, 2 * dim) };
  })();

  const normed = layernorm({
    input: x,
    weight: new Float32Array(dim).fill(1),
    bias: new Float32Array(dim),
    N: seq,
    D: dim,
    eps: 1e-6,
  });
  for (let s = 0; s < seq; s += 1) {
    for (let c = 0; c < dim; c += 1) {
      const at = s * dim + c;
      normed[at] = normed[at]! * (1 + finalMod.scale[c]!) + finalMod.shift[c]!;
    }
  }

  const outPatchDim = patchSpatial * patchSpatial * patchTemporal * cfg.outChannels;
  const projected = linear(
    normed,
    weights.get("net.final_layer.linear.weight"),
    seq,
    dim,
    outPatchDim,
    weights.has("net.final_layer.linear.bias") ? weights.get("net.final_layer.linear.bias") : undefined,
  );

  return unpatchify(projected, cfg.outChannels, T, H, W, patchSpatial, patchTemporal);
}
