#!/usr/bin/env python3
"""Bakes the sampler's schedule and one denoising step, from Z-Image's own code.

The schedule is six lines of arithmetic, which is exactly why it gets written
from memory and is exactly why that is a bad idea. Four things in it are easy
to get plausibly wrong, and each produces images rather than errors:

  - `linspace(1000, 1, steps + 1)[:-1]` — `steps + 1` points with the last
    dropped, not `steps` points. The difference is the size of the first step.
  - `sigma = shift * s / (1 + (shift - 1) * s)`, with `shift` defaulting to
    **3.0** in the generator (`BASE_SHIFT`/`MAX_SHIFT` in the config belong to a
    resolution-dependent path this one does not take).
  - A final `sigma = 0` is appended, so the last step lands on a clean latent.
  - The model is called with `(1000 - t) / 1000`, **reversed**, and its output
    is **negated** before the step: Z-Image predicts negative noise
    (`zimage_generate_image.py:604`).

Those last two cancel out in any test that compares a port against itself,
which is why they are baked from upstream here instead.

    /home/m96-chan/project/therdparty/musubi-tuner/.venv/bin/python \\
        examples/zimage/tools/gen_sampler_golden.py
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import torch

MUSUBI = Path("/home/m96-chan/project/therdparty/musubi-tuner/src")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=Path(__file__).resolve().parent.parent / "fixtures")
    ap.add_argument("--steps", type=int, default=8)
    ap.add_argument("--shift", type=float, default=3.0, help="the generator's --flow_shift default")
    args = ap.parse_args()

    if not MUSUBI.exists():
        sys.exit(f"musubi-tuner not found at {MUSUBI}")
    sys.path.insert(0, str(MUSUBI))
    from musubi_tuner.zimage import zimage_config, zimage_utils

    torch.set_grad_enabled(False)
    torch.manual_seed(0)

    timesteps, sigmas = zimage_utils.get_timesteps_sigmas(args.steps, args.shift)

    # One step of the Euler update, on a small tensor, so a port can check the
    # arithmetic and not merely the schedule.
    sample = torch.randn(2, 3)
    model_output = torch.randn(2, 3)
    stepped = [
        zimage_utils.step(model_output, sample, sigmas, i).reshape(-1).tolist()
        for i in range(args.steps)
    ]

    # What the generator feeds the model, per step: the reversed timestep.
    model_t = [((1000.0 - float(t)) / 1000.0) for t in timesteps]

    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "sampler.golden.json").write_text(json.dumps({
        "note": "Generated by tools/gen_sampler_golden.py from Z-Image's own scheduler. Do not hand-edit.",
        "torch": torch.__version__,
        "steps": args.steps,
        "shift": args.shift,
        "numTrainTimesteps": zimage_config.DEFAULT_SCHEDULER_NUM_TRAIN_TIMESTEPS,
        "defaults": {
            "inferenceSteps": zimage_config.DEFAULT_INFERENCE_STEPS,
            "guidanceScale": zimage_config.DEFAULT_GUIDANCE_SCALE,
            "flowShift": 3.0,
            "vaeScalingFactor": zimage_config.ZIMAGE_VAE_SCALING_FACTOR,
            "vaeShiftFactor": zimage_config.ZIMAGE_VAE_SHIFT_FACTOR,
            "vaeScaleFactor": zimage_config.ZIMAGE_VAE_SCALE_FACTOR,
        },
        "timesteps": [float(t) for t in timesteps],
        "sigmas": [float(s) for s in sigmas],
        "modelTimesteps": model_t,
        "step": {
            "sample": sample.reshape(-1).tolist(),
            "modelOutput": model_output.reshape(-1).tolist(),
            "results": stepped,
        },
    }, indent=2) + "\n")

    print(f"steps={args.steps} shift={args.shift}")
    print(f"timesteps: {[round(float(t), 3) for t in timesteps]}")
    print(f"sigmas:    {[round(float(s), 5) for s in sigmas]}")
    print(f"model t:   {[round(t, 5) for t in model_t]}")


if __name__ == "__main__":
    main()
